# Description

Create a n-by-m matrix containing the even integers from 2 to (n x m)x2. Create a second m-by-2 matrix containing the random integers of 4 or 9 with a given random seed s. Print these two matrices and their matrix multiplication. (hint: for the second matrix, please generate a matrix with a random number of 0 or 1 and use a mask to change them to 4 or 9)

# Input 

n,m,s

# Output

- A n-by-m matrix containing the even integers from 2 through (n x m)x2
- A m-by-2 matrix containing the random integers of 4 or 9 with a given random seed s
- A resulting n-by-2 matrix

## Reading Input (given)
The following lines of code will help you read in the input integer

In [1]:
# str_in = input()

In [2]:
str_in = '3,5,12'

In [9]:
import numpy as np

In [7]:
import numpy as np
str_in = '3,5,12'

class Solution:
    def __init__(self, str_in):
        self.str_in = str_in
        arr = np.array([int(x) for x in str_in.split(',')])
        s = arr[2]
        n = arr[0]
        m = arr[1]
        self.s = s
        self.n = n
        self.m = m

    def __generate_even_matrix(self):
        even_numbers = np.arange(2, 2 * (self.n*self.m) + 1, 2)
        even_matrix = even_numbers.reshape(self.n, self.m)
        return even_matrix
    
    def __print_first_matrix(self):
        even_matrix = self.__generate_even_matrix()
        print('The first matrix is:')
        print(even_matrix)

    def __generate_second_matrix(self):
        np.random.seed(self.s)
        second_matrix = np.random.randint(0, 2, size=(self.m, 2))
        bool_second_matrix = np.where(second_matrix == 0, 4, 9)
        return bool_second_matrix

    def __print_second_matrix(self): 
        bool_second_matrix = self.__generate_second_matrix()
        print('The second matrix is:')
        print(bool_second_matrix)

    def __generate_third_matrix(self):
        even_matrix = self.__generate_even_matrix()
        bool_second_matrix = self.__generate_second_matrix()
        # third_matrix = even_matrix@bool_second_matrix
        third_matrix = np.dot(even_matrix, bool_second_matrix)
        return third_matrix
    
    def __print_third_matrix(self):
        third_matrix = self.__generate_third_matrix()
        print('The multiplication results of the first and second matrices are:')
        print(third_matrix)
    
    def print_all_solution(self):
        self.__print_first_matrix()
        self.__print_second_matrix()
        self.__print_third_matrix()

sol = Solution(str_in)
sol.print_all_solution()



The first matrix is:
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]
The second matrix is:
[[9 9]
 [4 9]
 [9 4]
 [9 9]
 [4 4]]
The third matrix is:
[[200 190]
 [550 540]
 [900 890]]


In [8]:
even_numbers = np.arange(2, 2 * (n*m) + 1, 2)
even_matrix = even_numbers.reshape(n, m)
even_matrix


array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

# Main Program (write your main program here and copy and paste them to online judge when you are confident.)