# Description
You are to use NumPy's random module with a given seed to generate random integers, ranging from 0 to 120 ($0 \le x < 120$), in a 1D array of size $n$. Adjust the grade records below 40 to 40 and above 100 to 100. Then, change the shape of the 1D array into an $r$ by $c$ 2D array. Last, you are to find those rows with a mean larger than the threshold $m$ and report the 2D array and the sum of those rows. You should report dimension inconsistency if the 1D array cannot be converted into an $r$ by $c$ 2D array. 

# Input
A string containing the following information:
- n (size of the 1D array)</br>
- r (number of rows)</br>
- c (number of columns)</br>
- m (an integer threshold)</br>
- seed (random seed)</br>

# Output
You should report 'Dimension is inconsistent' or 
- the 2D array
- the sum of those rows with a mean larger than m


## Reading Input (given)
The following lines of code will help you read in the input integers

In [1]:
str_in = input()
# str_in = '12, 3, 3, 60, 0'
# str_in = '12, 4, 3, 60, 0'
# str_in = '6, 2, 3, 80, 42'

# Main Program (write your main program here and copy and paste them to online judge when you are confident.)

In [1]:
import numpy as np
# str_in = input()


In [27]:
str_in = '6, 2, 3, 80, 42'

In [2]:
import numpy as np
# str_in = input()
str_in = '12, 4, 3, 60, 0'
class Solution:
    def __init__(self, str_in):
        """
        Initializes the Solution class by parsing the input string and setting attributes.

        Parameters
        ----------
        str_in : str
            A string containing the size of the 1D array, number of rows, 
            number of columns, an integer threshold, and a random seed, 
            separated by commas.
        """
        self.str_in = str_in
        self.arr = np.array([int(x) for x in str_in.split(', ')])
        self.n = self.arr[0]  # n is size of the 1D array
        self.r = self.arr[1]  # r is number of rows
        self.c = self.arr[2]  # c is number of columns
        self.m = self.arr[3]  # m is an integer threshold
        self.seed = self.arr[4]  # seed is random seed

    def __check_dimension_consistent(self):
        """
        Checks if the dimensions are consistent.

        Returns
        -------
        bool
            True if dimensions are consistent, False otherwise.
        """
        return self.r > 0 and self.c > 0 and self.r * self.c == self.n
    
    def generate_matrix(self):
        """
        Generates a 2D array with random integers between 0 and 120, 
        then clips the values to be between 40 and 100.

        Returns
        -------
        np.ndarray
            The generated 2D array.
        """
        np.random.seed(self.seed)
        self.matrix = np.random.randint(0, 120, (self.r, self.c))  # Generate a 2D array with random integers between 0 and 120
        self.matrix = np.clip(self.matrix, 40, 100)  # Clip the values to be between 40 and 100
        self.matrix = self.matrix.reshape(self.r, self.c)  # Reshape the 2D array
    
    def __print_matrix_sol(self):
        """
        Generates and prints the adjusted 2D matrix.
        """
        self.generate_matrix()
        print('The adjusted 2D array')
        print(self.matrix)

    def __print_sum_of_rows_with_mean_larger_than_threshold(self):
        """
        Calculates and prints the sum of those rows with a mean larger than the threshold.
        """
        row_means = self.matrix.mean(axis=1)  # Calculate the mean of each row
        rows_mean_with_over_threshold = self.matrix[row_means > self.m]  # Select rows with mean larger than the threshold
        row_sums = np.sum(rows_mean_with_over_threshold, axis=1)  # Sum of those rows with a mean larger than the threshold
        print(f'The sum of those rows with a mean larger than {self.m}')
        print(row_sums)

    def print_sol(self):
        """
        Prints the solution, including the adjusted 2D matrix and the sum of rows with a mean larger than the threshold.
        """
        if self.__check_dimension_consistent():
            self.__print_matrix_sol()
            self.__print_sum_of_rows_with_mean_larger_than_threshold()
        else:
            print('Dimension is inconsistent')

sol = Solution(str_in)
sol.print_sol()

The adjusted 2D array
[[ 44  47 100]
 [ 64  67  67]
 [100  40  83]
 [ 40 100  40]]
The sum of those rows with a mean larger than 60
[191 198 223]


In [15]:
row_means = matrix.mean(axis=1)
row_means

array([63.66666667, 66.        , 74.33333333, 60.        ])

In [19]:
row_means > 70

array([False, False,  True, False])

In [20]:
rows_mean_with_over_threshold = matrix[row_means > 70]
rows_mean_with_over_threshold

array([[100,  40,  83]])