# Description

Consider the grade records containing five exams for class 01 and class 02, where class 01 has n students and class 02 has m students. Prompt the online judge for a string containing the random seed, the number of students in class01 (n), and the number of students in class02 (m). Create an array of n by 5 for class 01 and an array of m by 5 for class 02 with randomly generated grades between 40 – 100 (100 included). Output the mean and standard deviation with two decimal places for class01 and class02. Output the mean and standard deviation with two decimal places of each exam for all students.

# Input

A string: ‘s, n, m’ where s is the random seed, n is the number of students in class01, and m is the number of students in class02.

# Output

- A n by 5 array (grade records for class01)
- A m by 5 array (grade records for class02)
- A (n+m) by 5 array (grade records for both classes)
- The mean and standard deviation with two decimal places for class01 and class02
- The mean and standard deviation of each exam with two decimal places for all students.

## Reading Input (given)
The following lines of code will help you read in the input string

In [83]:
str_in = input()

In [84]:
type(str_in)

str

In [ ]:
#A sample input string for testing
str_in = '42, 3, 2'
# str_in = '6, 4, 3'

# Main Program (write your main program here and copy and paste them to online judge when you are confident.)

In [ ]:
import numpy as np
arr = np.array([str(x) for x in str_in.split(',')])

In [ ]:
m = arr[2].astype(int)
n = arr[1].astype(int)
s = arr[0].astype(int)

In [ ]:
import json

input_data = {
    'random seed': 42,
    'number of students in class01': 3,
    'number of students in class02': 2
}

print(json.dumps(input_data, indent=4))

In [ ]:
np.random.seed(s)
class01_matrix = np.random.randint(40, 101, (n, 5))
class01_matrix

In [ ]:
np.random.seed(s)
class01_matrix = np.random.randint(40, 101, (n, 5))
class01_matrix

In [1]:
import numpy as np

class Solution:
    def __init__(self, str_in):
        self.str_in = str_in
        self.arr = np.array([int(x) for x in str_in.split(', ')])
        self.s = self.arr[0]
        self.n = self.arr[1]
        self.m = self.arr[2]
    
    def build_random_num_matrix(self):
        np.random.seed(self.s)
        self.class01_matrix = np.random.randint(40, 101, (self.n, 5))
        self.class02_matrix = np.random.randint(40, 101, (self.m, 5))
        return self.class01_matrix, self.class02_matrix
    
    def __add_both_class_matrix(self):
        self.both_class_matrix = np.vstack((self.class01_matrix, self.class02_matrix))
        return self.both_class_matrix
    
    def __get_exam_mean_std(self, exam_num):
        exam_idx = exam_num - 1
        return np.mean(self.both_class_matrix[:,exam_idx]), np.std(self.both_class_matrix[:,exam_idx])
    
    def print_all_matrix(self):
        self.both_class_matrix = self.__add_both_class_matrix()
        print('Grades for class01 are:', self.class01_matrix)
        print('Grades for class02 are:', self.class02_matrix)
        print('Grades for both classes are:', self.both_class_matrix)

        # self.both_class_matrix = self.__add_both_class_matrix()
        
        # def format_matrix(matrix):
        #     return "[[" + "]\n [".join(" ".join(f"{x:3d}" for x in row) for row in matrix) + "]]"
        
        # print('Grades for class01 are:')
        # print(format_matrix(self.class01_matrix))
        
        # print('Grades for class02 are:')
        # print(format_matrix(self.class02_matrix))
        
        # print('Grades for both classes are:')
        # print(format_matrix(self.both_class_matrix))


    def print_all_result_mean_std(self):
        
        print('The mean and std for class01 are:', f"{np.mean(self.class01_matrix):.2f},",f"{np.std(self.class01_matrix):.2f}")
        print('The mean and std for class02 are:', f"{np.mean(self.class02_matrix):.2f},",f"{np.std(self.class02_matrix):.2f}")
        for i in range(5):
            exam_num = i + 1
            mean, std = self.__get_exam_mean_std(exam_num)
            print(f'The mean and std for exam0{exam_num} are:', f"{mean:.2f},", f"{std:.2f}")

str_in = '6, 4, 3'
sol = Solution(str_in)
sol.build_random_num_matrix()
sol.print_all_matrix()

sol.print_all_result_mean_std()


Grades for class01 are: [[50 49 75 60 82]
 [85 55 82 56 65]
 [41 51 53 97 66]
 [87 73 84 86 44]]
Grades for class02 are: [[73 48 42 52 60]
 [67 71 42 45 66]
 [55 65 62 90 83]]
Grades for both classes are: [[50 49 75 60 82]
 [85 55 82 56 65]
 [41 51 53 97 66]
 [87 73 84 86 44]
 [73 48 42 52 60]
 [67 71 42 45 66]
 [55 65 62 90 83]]
The mean and std for class01 are: 67.05, 16.45
The mean and std for class02 are: 61.40, 13.93
The mean and std for exam01 are: 65.43, 16.26
The mean and std for exam02 are: 58.86, 9.83
The mean and std for exam03 are: 62.86, 16.60
The mean and std for exam04 are: 69.43, 19.37
The mean and std for exam05 are: 66.57, 12.33


Sample Input 1

In [ ]:
42, 3, 2

Sample Output 1

In [ ]:
# Grades for class01 are:
# [[ 78  91  68  54  82]
#  [ 47 100  60  78  97]
#  [ 58  62  50  50  63]]
# Grades for class02 are:
# [[92 75 79 63 42]
#  [61 92 41 63 83]]
# Grades for both classes are:
# [[ 78  91  68  54  82]
#  [ 47 100  60  78  97]
#  [ 58  62  50  50  63]
#  [ 92  75  79  63  42]
#  [ 61  92  41  63  83]]
# The mean and std for class01 are: 69.20, 16.89
# The mean and std for class02 are: 69.10, 17.43
# The mean and std for exam01 are: 67.20, 15.89
# The mean and std for exam02 are: 84.00, 13.67
# The mean and std for exam03 are: 59.60, 13.31
# The mean and std for exam04 are: 61.60, 9.65
# The mean and std for exam05 are: 73.40, 19.06

Sample Input 2

6, 4, 3

Sample Output 2

In [ ]:
# Grades for class01 are:
# [[50 49 75 60 82]
#  [85 55 82 56 65]
#  [41 51 53 97 66]
#  [87 73 84 86 44]]
# Grades for class02 are:
# [[73 48 42 52 60]
#  [67 71 42 45 66]
#  [55 65 62 90 83]]
# Grades for both classes are:
# [[50 49 75 60 82]
#  [85 55 82 56 65]
#  [41 51 53 97 66]
#  [87 73 84 86 44]
#  [73 48 42 52 60]
#  [67 71 42 45 66]
#  [55 65 62 90 83]]
# The mean and std for class01 are: 67.05, 16.45
# The mean and std for class02 are: 61.40, 13.93
# The mean and std for exam01 are: 65.43, 16.26
# The mean and std for exam02 are: 58.86, 9.83
# The mean and std for exam03 are: 62.86, 16.60
# The mean and std for exam04 are: 69.43, 19.37
# The mean and std for exam05 are: 66.57, 12.33

Submit to OJ code: Partial Accepte

In [3]:
import numpy as np

str_in = input()
class Solution:
    def __init__(self, str_in):
        self.str_in = str_in
        self.arr = np.array([int(x) for x in str_in.split(', ')])
        self.s = self.arr[0]
        self.n = self.arr[1]
        self.m = self.arr[2]
    
    def build_random_num_matrix(self):
        np.random.seed(self.s)
        self.class01_matrix = np.random.randint(40, 101, (self.n, 5))
        self.class02_matrix = np.random.randint(40, 101, (self.m, 5))
        return self.class01_matrix, self.class02_matrix
    
    def __add_both_class_matrix(self):
        self.both_class_matrix = np.vstack((self.class01_matrix, self.class02_matrix))
        return self.both_class_matrix
    
    def __get_exam_mean_std(self, exam_num):
        exam_idx = exam_num - 1
        return np.mean(self.both_class_matrix[:,exam_idx]), np.std(self.both_class_matrix[:,exam_idx])
    
    def print_all_matrix(self):
        self.both_class_matrix = self.__add_both_class_matrix()
        print('Grades for class01 are:')
        print(self.class01_matrix)
        print('Grades for class02 are:')
        print(self.class02_matrix)
        print('Grades for both classes are:')
        print(self.both_class_matrix)

    def print_all_result_mean_std(self):
        
        print('The mean and std for class01 are:', f"{np.mean(self.class01_matrix):.2f},",f"{np.std(self.class01_matrix):.2f}")
        print('The mean and std for class02 are:', f"{np.mean(self.class02_matrix):.2f},",f"{np.std(self.class02_matrix):.2f}")
        for i in range(5):
            exam_num = i + 1
            mean, std = self.__get_exam_mean_std(exam_num)
            print(f'The mean and std for exam0{exam_num} are:', f"{mean:.2f},", f"{std:.2f}")

sol = Solution(str_in)
sol.build_random_num_matrix()
sol.print_all_matrix()
sol.print_all_result_mean_std()


Grades for class01 are:
[[50 49 75 60 82]
 [85 55 82 56 65]
 [41 51 53 97 66]
 [87 73 84 86 44]]
Grades for class02 are:
[[73 48 42 52 60]
 [67 71 42 45 66]
 [55 65 62 90 83]]
Grades for both classes are:
[[50 49 75 60 82]
 [85 55 82 56 65]
 [41 51 53 97 66]
 [87 73 84 86 44]
 [73 48 42 52 60]
 [67 71 42 45 66]
 [55 65 62 90 83]]
The mean and std for class01 are: 67.05, 16.45
The mean and std for class02 are: 61.40, 13.93
The mean and std for exam01 are: 65.43, 16.26
The mean and std for exam02 are: 58.86, 9.83
The mean and std for exam03 are: 62.86, 16.60
The mean and std for exam04 are: 69.43, 19.37
The mean and std for exam05 are: 66.57, 12.33
